apiVersion: v1
kind: Namespace
metadata:
  name: gpu-workloads
  labels:
    purpose: inference
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    purpose: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    purpose: gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    purpose: policy
